name: Correctness
on: [push]

jobs:
  correctness:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1

      # Fix SQLite issue. Tests pass locally but no in this Action
      # See https://stackoverflow.com/questions/72165451/pytest-is-failing-on-github-actions-but-succeeds-locally
      - run: |
          wget https://sqlite.org/2022/sqlite-autoconf-3380500.tar.gz
          tar -xvf sqlite-autoconf-3380500.tar.gz
      - run: |
          ./configure
          make
          sudo make install
          export PATH="/usr/local/lib:$PATH"
        working-directory: sqlite-autoconf-3380500

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2.2
      - name: Create environment
        run:  poetry install
      - name: Pylint source
        run:  poetry run pylint ./tds
      - name: Pylint tests
        run:  poetry run pylint ./tests
      - name: Pytest
        run:  poetry run pytest
